version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASS: password
      DB_NAME: musicDb
      DB_HOST: db
      JWT_SECRET: s3cres3cret
    volumes:
      - ./backend:/music-api
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
