version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASS: password
      DB_NAME: musicDb
      DB_HOST: db
      DB_TEST_HOST: db-test
      JWT_SECRET: s3cres3cret
    volumes:
      - ./backend:/music-api
    restart: always
    depends_on:
      - db
      - db-test
  db:
    image: mysql
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .db/data/mysql:/var/lib/mysql
  db-test:
    image: mysql
    container_name: mysql-test-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .db/data-test/mysql:/var/lib/mysql
    ports:
      - 3307:3306
