version: '3'

services:
  frontend:
    build: ./frontend
    command: sh -c "npm run dev"
    container_name: pc-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app/frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/
      NEXT_PUBLIC_NETWORK_API_URL: http://fullstack_project_backend_1:3001/
  backend:
    build: ./backend
    command: sh -c "npm run db-migrate && npm run dev"
    container_name: pc-backend
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASS: password
      DB_NAME: musicDb
      DB_HOST: db
      DB_TEST_HOST: db-test
      JWT_SECRET: s3cres3cret
    volumes:
      - ./backend:/home/app/backend
    restart: always
    depends_on:
      - db
      - db-test
  db:
    image: mysql
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data/mysql:/var/lib/mysql
  db-test:
    image: mysql
    container_name: mysql-test-container
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data-test/mysql:/var/lib/mysql
    ports:
      - 3307:3306
